### ISSUE TITLE
error while load trace with perf

### ISSUE THREAD

**Issue by slowpy** [microsoft/Microsoft-Performance-Tools-Linux-Android#109]
it pop a wind title "error while querying table cpu scheduler events"

[PerfettoCds.PerfettoDataProcessor]: Verbose - Query for PerfettoExpectedFrameEvent returning 434 rows completed in 0.0064454s at 05/06/2023 06:26:49.376 UTC
Loaded Local Preferences from C:\Users\dd\AppData\Local\Windows Performance Analyzer\Preferences.xml
Error: Error while querying table  CPU Scheduler Events. Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at System.Linq.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument)
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at PerfettoCds.Pipeline.CompositeDataCookers.PerfettoCpuSchedEventCooker.PopulateCpuWakeEvents(IDataExtensionRetrieval requiredData, ProcessedEventData`1 threadData, ProcessedEventData`1 processData) in D:\a\1\s\Microsoft-Performance-Tools-Linux-Android\PerfettoCds\Pipeline\CompositeDataCookers\PerfettoCpuSchedEventCooker.cs:line 143
   at PerfettoCds.Pipeline.CompositeDataCookers.PerfettoCpuSchedEventCooker.PopulateCpuSchedulingEvents(IDataExtensionRetrieval requiredData, ProcessedEventData`1 threadData, ProcessedEventData`1 processData) in D:\a\1\s\Microsoft-Performance-Tools-Linux-Android\PerfettoCds\Pipeline\CompositeDataCookers\PerfettoCpuSchedEventCooker.cs:line 62
   at PerfettoCds.Pipeline.CompositeDataCookers.PerfettoCpuSchedEventCooker.OnDataAvailable(IDataExtensionRetrieval requiredData) in D:\a\1\s\Microsoft-Performance-Tools-Linux-Android\PerfettoCds\Pipeline\CompositeDataCookers\PerfettoCpuSchedEventCooker.cs:line 54
   at Microsoft.Performance.SDK.Runtime.Extensibility.DataExtensions.DataCookers.CompositeDataCookerReference.CreateInstance(IDataExtensionRetrieval requiredData)
   at Microsoft.Performance.SDK.Runtime.Extensibility.DataExtensions.ProcessingSystemCompositeCookers.GetOrCreateCompositeCooker(DataCookerPath cookerPath, Func`2 createDataRetrieval)
   at Microsoft.Performance.SDK.Runtime.Extensibility.DataExtensions.ProcessingSystemCompositeCookers.GetCookerOutput(DataCookerPath dataCookerPath)
   at Microsoft.Performance.SDK.Runtime.Extensibility.FilteredDataRetrieval.GetCompositeDataRetrieval(DataCookerPath cookerPath)
   at Microsoft.Performance.SDK.Runtime.Extensibility.FilteredDataRetrieval.GetCompositeDataRetrieval(DataOutputPath outputPath)
   at Microsoft.Performance.SDK.Runtime.Extensibility.FilteredDataRetrieval.QueryCompositeOutput[T](DataOutputPath dataOutputPath)
   at Microsoft.Performance.SDK.Runtime.Extensibility.FilteredDataRetrieval.QueryOutput[T](DataOutputPath dataOutputPath)
   at PerfettoCds.Pipeline.Tables.PerfettoCpuSchedTable.IsDataAvailable(IDataExtensionRetrieval tableData) in D:\a\1\s\Microsoft-Performance-Tools-Linux-Android\PerfettoCds\Pipeline\Tables\PerfettoCpuSchedTable.cs:line 121
   --- End of inner exception stack trace ---
   at Microsoft.Performance.Threading.BackgroundWorkManager.Send(Action action)
   at Microsoft.Performance.Threading.BackgroundWorkManager.SendFunc[TResult](Func`1 func)
   at Microsoft.Performance.Shell.Bridge.ConvertToHdv.ProcessingSourceTableToHdvViewModelSourceAdaptor.IsDataAvailable()

**Comment by ivberg** [comment]
Thanks for reporting @slowpy. Do you happen to have a trace you can attach or send to repro the issue? Alternatively (but less ideally) if you have specific instructions to get such a trace that can be an alternative as well.

**Comment by slowpy** [comment]
[trace.zip](https://github.com/microsoft/Microsoft-Performance-Tools-Linux-Android/files/11429194/trace.zip)

**Comment by ivberg** [comment]
Closing - fixed in 1.5.3 - Perfetto Bug Fix error parsing CPU scheduling wake events
