### ISSUE TITLE
LTTng - UnsupportedFileException when trying to process LTTng trace folder (.ctf file works)

### ISSUE THREAD

**Issue by ivberg** [microsoft/Microsoft-Performance-Tools-Linux-Android#6]
Seen in Release 0.8.0

LTTngDriver throws this error when trying to process a LTTng trace folder. The same folder zipped as .ctf file works. This used to work in the past which I re-verified on the same trace with an old drop. The same issue/error repro's in the WPA UI when opening the folder.

(base) DESKTOP:~/LTTngDriverDebug/netcoreapp3.1$ ./LTTngDriver.exe ~/LTTngDriverDebug/netcoreapp3.1/kernel
ExtensionDirectory:
Loaded all in 00:00:00.7319867
CTF Path:/home/ivberg/LTTngDriverDebug/netcoreapp3.1/kernel
Microsoft.Performance.Toolkit.Engine.UnsupportedFileException: The given file is not supported by any known processors
   at Microsoft.Performance.Toolkit.Engine.Engine.AddFile(String filePath)
   at LTTngDriver.Program.Run() in C:\src\Microsoft-Performance-Tools-Linux\LTTngDriver\Program.cs:line 59
   at LTTngDriver.Program.Main(String[] args) in C:\src\Microsoft-Performance-Tools-Linux\LTTngDriver\Program.Main.cs:line 15
FilePath: /home/ivberg/LTTngDriverDebug/netcoreapp3.1/kernel

**Comment by Alois-xx** [comment]
I am new to CTF. I have found from a LTTNG tutorial a sample file https://lttng.org/blog/2018/03/21/lttng-scope-0.3-a-basic-tutorial/ which has a tarball of https://github.com/lttng/lttng-ref-traces/raw/master/traces/basic-kernel-analysis.tar.xz
The trace data generated by lttng is a folder of channel files 
![image](https://user-images.githubusercontent.com/408821/109808970-0d621580-7c28-11eb-871d-631280161681.png)

To make it ctf it is sufficient to zip the complete folder, rename to ctf and load it in WPA? I have tried that but I get then 

```
Unable to process 'file:///C:/basic-kernel-analysis/kernel.ctf': System.Exception: No events - failure processing .ctf
   at PerfCds.PerfSourceParser.ProcessSource(ISourceDataProcessor`3 dataProcessor, ILogger logger, IProgress`1 progress, CancellationToken cancellationToken) in D:\a\1\s\Microsoft-Performance-Tools-Linux\PerfCds\PerfSourceParser.cs:line 132
   at Microsoft.Performance.SDK.Runtime.Extensibility.SourceProcessingSession`3.ProcessSource(ILogger logger, IProgress`1 progress, CancellationToken cancellationToken)
   at Microsoft.Performance.SDK.Processing.CustomDataProcessorBaseWithSourceParser`3.ProcessAsyncCore(IProgress`1 progress, CancellationToken cancellationToken)
   at Microsoft.Performance.SDK.Processing.CustomDataProcessorBase.ProcessAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Microsoft.Performance.SDK.Runtime.CustomDataSourceExecutor.ExecuteAsync(CancellationToken cancellationToken)
Unable to process 'file:///C:/basic-kernel-analysis/kernel.ctf': System.Exception: No events - failure processing .ctf
   at LTTngCds.LTTngSourceParser.ProcessSource(ISourceDataProcessor`3 dataProcessor, ILogger logger, IProgress`1 progress, CancellationToken cancellationToken) in D:\a\1\s\Microsoft-Performance-Tools-Linux\LTTngCds\LTTngSourceParser.cs:line 135
   at Microsoft.Performance.SDK.Runtime.Extensibility.SourceProcessingSession`3.ProcessSource(ILogger logger, IProgress`1 progress, CancellationToken cancellationToken)
   at Microsoft.Performance.SDK.Processing.CustomDataProcessorBaseWithSourceParser`3.ProcessAsyncCore(IProgress`1 progress, CancellationToken cancellationToken)
   at Microsoft.Performance.SDK.Processing.CustomDataProcessorBase.ProcessAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Microsoft.Performance.SDK.Runtime.CustomDataSourceExecutor.ExecuteAsync(CancellationToken cancellationToken)
Unable to process any data sources.
```

I have copied the extensions of your drop to "C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\CustomDataSources\MicrosoftPerfToolkitAddins". WPA comes then up properly.

**Comment by ivberg** [comment]
Hey @Alois-xx I think you were doing the workaround (zip/rename to ctf) the right way, but there does indeed seem to be an issue reading that trace. I can repro as well with the same error you got. We will look into it @ndecarli 

I was able to open the Trace with another OSS tool (Trace Compass) so the trace itself looks fine. Maybe you should open another GitHub issue for this specific issue with "No Events"?

I know you were new to LTTng / CTF and trying to open an existing reference trace from the tutorial which we want to work. However, we haven't had any issues (that we know of) opening newer LTTng traces from systems using instructions like these. Perhaps you want to give it a try capturing your own trace as well?
https://github.com/microsoft/Microsoft-Performance-Tools-Linux/blob/develop/LinuxTraceLogCapture.md

P.S. Hopefully in the near term this workaround for this issue will be solved and you can open folders in Microsoft-Performance-Tools-Linux. The SDK changes that support this are almost ready, and then we can consume the SDK update with a fix for this issue #6 opening folders.

**Comment by Alois-xx** [comment]
@ivberg: Can I record lttng with WSL2 on Windows 10 1909? I am preparing some slides for an internal dev conference where I wanted to show this working at least once on my machine. Or is a VM the only option here? 
The post https://github.com/microsoft/WSL/issues/6137 mentions that I need to compile a kernel on my own. Is it really that complicated? 
I have compiled a kernel but the instruction to build lttng seem not to be complete. 

```
xx:~/WSL2/WSL2-Linux-Kernel/lttng-modules$ make
make -C /lib/modules/5.4.72-microsoft-standard-WSL2/build M=/home/alois/WSL2/WSL2-Linux-Kernel/lttng-modules CONFIG_LTTNG=m CONFIG_LTTNG_CLOCK_PLUGIN_TEST=m modules
make[1]: *** /lib/modules/5.4.72-microsoft-standard-WSL2/build: No such file or directory.  Stop.
make: *** [Makefile:111: modules] Error 2
xx:~/WSL2/WSL2-Linux-Kernel/lttng-modules$
```

**Comment by ivberg** [comment]
Yes you should be able to record on WSL2 but you will need to follow the custom compile instructions that you linked. You don't need the compile the whole kernel, just the enough for the module to be linked. Hopefully we can improve this in the future.

The other option is to test in a VM where LTTng is available as a package - https://lttng.org/download/

P.S. This is a separate issue than this thread. I would recommend putting any WSL2 LTTng discussions under that other issue under the WSL2 project.
